name: Run prettier
on:
  push:
    branches: ['*']
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # Pull the code
      - name: Checkout
        uses: actions/checkout@v2
      #with:
      #persist-credentials: false
      #fetch-depth: 0

      #  Generating static files/Build
      - name: Generate static vuepress files
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run prettier:check