
   
name: VuePress build
on:
  push:
    branches: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Pull the code
      - name: Checkout
        uses: actions/checkout@v2

      #  Generating static files/Build
      - name: Install node v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - name: Build vuepress html site
        run: npm run docs:build
